### ISSUE TITLE
Boundary layer - move data import into mapping.yaml

### ISSUE THREAD

**Issue by eva-j** [openmaptiles/openmaptiles#1156]
After discussion on Slack (osmus.slack.com), it would be good to move importing borders from omt-tools (using https://github.com/pnorman/osmborder) to `mapping.yaml`. It could be probably joined with the mapping we do now for disputed borders (maybe just remove there `claimed_by: [__any__]` ?) 
https://github.com/openmaptiles/openmaptiles/blob/master/layers/boundary/mapping.yaml#L89-L124
This way we would have only `osm_border_linestring` table, no `osm_border_disp_linestring` anymore.
___
Comment of @pnorman:

I was looking at if osmborder can be replaced by imposm functionality for work, and it turns out it can - at least partially. This can be done by creating a relation_member table with imposm,
```
tables:
  admin_members:
    type: relation_member
    columns:
    - name: osm_id
      type: id
    - name: member
      type: member_id
    - name: type
      type: member_type
    - name: admin_level
      key: admin_level
      type: integer
    - name: geometry
      type: geometry
    relation_types: [boundary]
    mapping:
      boundary: [administrative]
```
The SQL to generate tiles can be something like
```
SELECT DISTINCT ON (member, type)
geometry, admin_level
FROM osm_admin_members
WHERE type = 1
AND admin_level > 0
ORDER BY member, type, admin_level ASC;
```
___
This change enables to do attribute edits on import, requested e.g. in https://github.com/openmaptiles/openmaptiles/issues/623.
