### ISSUE TITLE
Include rivers in generalized water polygons

### ISSUE THREAD

**Issue by lukasmartinelli** [openmaptiles/openmaptiles#120]
Reported in https://github.com/openmaptiles/klokantech-basic-gl-style/issues/3

That's actually bad because we exclude rivers for these zoom levels. We need to remove this constraint for the next rendering.

https://github.com/openmaptiles/openmaptiles/blob/master/layers/water/mapping.yaml#L28-L31

```
  # etldoc: imposm3 -> osm_water_polygon_gen1
  water_polygon_gen1:
    source: water_polygon
    sql_filter: area>500000 AND waterway = ''
    tolerance: 20
```
