### ISSUE TITLE
SRS and SRS have not impact on mbtile output

### ISSUE THREAD

**Issue by jt-helsinki** [openmaptiles/openmaptiles#1341]
This is appears to be a bug with generating tiles in alternative projections. 

If I change the `srs` and and `srid` values in the `openmaptiles.yaml` it appears that this has no impact on the generated tiles. Tiles appear to be always generated in WebMercator. 3587.

For example, a very basic example changing the srs to WGS84 till generates WebMercator (3857) tiles:

```
tileset:
  layers:
    - layers/water/water.yaml
    - layers/waterway/waterway.yaml
    - layers/landcover/landcover.yaml
    - layers/landuse/landuse.yaml
    - layers/mountain_peak/mountain_peak.yaml
    - layers/park/park.yaml
    - layers/boundary/boundary.yaml
    - layers/aeroway/aeroway.yaml
    - layers/transportation/transportation.yaml
    - layers/building/building.yaml
    - layers/water_name/water_name.yaml
    - layers/transportation_name/transportation_name.yaml
    - layers/place/place.yaml
    - layers/housenumber/housenumber.yaml
    - layers/poi/poi.yaml
    - layers/aerodrome_label/aerodrome_label.yaml
  name: OpenMapTiles
  version: 3.13.0
  id: openmaptiles
  description: "A tileset showcasing all layers in OpenMapTiles. https://openmaptiles.org"
  attribution: '<a href="https://www.openmaptiles.org/" target="_blank">&copy; OpenMapTiles</a> <a href="https://www.openstreetmap.org/copyright" target="_blank">&copy; OpenStreetMap contributors</a>'
  center: [0, 0, 1]
  bounds: [-180.0,-85.0511,180.0,85.0511]
  maxzoom: 9
  minzoom: 0
  pixel_scale: 256
  languages:
    - en # English, Latin
  defaults:
    srs: +proj=longlat +datum=WGS84 +no_defs
    datasource:
      srid: 4326
```

I've tried other SRS vales. Same result.

My process for generating the tiles is:

1. Change the SRS and SRID values
2. `make`
3. `make start-db`
4. `make import-data`
5. `make download area=finland` 
6. `make import-osm area=finland`
7. `make import-wikidata`
8. `make import-sql`
9. `make generate-tiles-pg`

If I check the `./build/openmaptiles.tm2source/data.yaml` file my specified projection is appears to be in the file as expected. For example:

```
...
- Datasource:
    dbname: openmaptiles
    extent:
    - -20037508.34
    - -20037508.34
    - 20037508.34
    - 20037508.34
    geometry_field: geometry
    host: postgres
    key_field: ''
    key_field_as_attribute: ''
    max_size: 512
    password: openmaptiles
    port: 5432
    srid: 4326
    table: (SELECT geometry, class, subclass FROM layer_landcover(!bbox!, z(!scale_denominator!)))
      AS t
    type: postgis
    user: openmaptiles
  id: landcover
  properties:
    buffer-size: 4
  srs: +proj=longlat +datum=WGS84 +no_defs
- Datasource:
    dbname: openmaptiles
    extent:
    - -20037508.34
    - -20037508.34
    - 20037508.34
    - 20037508.34
    geometry_field: geometry
    host: postgres
    key_field: ''
    key_field_as_attribute: ''
    max_size: 512
    password: openmaptiles
    port: 5432
    srid: 4326
    table: (SELECT geometry, class FROM layer_landuse(!bbox!, z(!scale_denominator!)))
      AS t
    type: postgis
    user: openmaptiles
  id: landuse
  properties:
    buffer-size: 4
  srs: +proj=longlat +datum=WGS84 +no_defs

...

```

Also, I saw this issue: https://github.com/openmaptiles/openmaptiles/issues/179 , which seems to suggest that this is in fact possible.
