### ISSUE TITLE
Configurable tile buffer size override

### ISSUE THREAD

**Issue by nyurik** [openmaptiles/openmaptiles#1345]
## Intro

Buffering is used to include data that is right outside of the tile. For roads, the buffer is usually set to 4 because that's an approximate width of the road - so if a road is drawn on a neighboring tile, and part of it should be visible on the current tile, the data for it is included. The buffer is much larger for text layers because the text often takes much more space than a single tile.

In theory (needs confirmation), buffer is not needed when drawing tiles in the browser using [MapLibre GL JS](https://github.com/maplibre/maplibre-gl-js), and possibly [OpenLayers](https://openlayers.org/) and [MapLibre GL Native](https://github.com/maplibre/maplibre-gl-native).  The buffer is needed when rendering tile as a raster image - usually done on a server. This means we can substantially reduce the size of each tile when we know that the server-side rendering is NOT used, but must keep it for server-side rendering use cases.

## Proposal

* Support [.env file](https://github.com/openmaptiles/openmaptiles/blob/master/.env) parameter `BUFFER_SIZE`, treated as an integer, to override all `buffer_size` values set in the layer files (e.g. [this one](https://github.com/openmaptiles/openmaptiles/blob/master/layers/aerodrome_label/aerodrome_label.yaml#L5)).  The ENV var would override all other buffer_size values proposed below.

* Optionally support a percentage value, where 100% would mean no change to the size set in the layer files.

* Optionally support buffer size override in the [main config yaml file](https://github.com/openmaptiles/openmaptiles/blob/master/openmaptiles.yaml). This value would override buffer size values defined in the individual layer yaml files. See below for override order. 

```yaml
tileset:
  layers:
    ...
  name: ...
  buffer_size: 0  # or possibly a percentage, same as for .env file above
```

* Optionally support buffer size override for each layer using the method proposed in https://github.com/openmaptiles/openmaptiles-tools/issues/377:

```yaml
tileset:
  layers:
    - layers/water/water.yaml
    - file: layers/waterway/waterway.yaml
      buffer_size: 0  # could also use percentage here, same as for .env file above
```

### Override order
The OMT tools will pick the first buffer size it finds from this list:

* `BUFFER_SIZE` in the `.env` file
* Per-layer override in the main config file set in `tileset.layers[].buffer_size`
* Top level value in the main config file -- `tileset.buffer_size`
* Value set in the layer itself (what we have now) -- `layer.buffer_size` in the layer config file.
