### ISSUE TITLE
Use Varnish with apache2 and docker compose

### ISSUE THREAD

**Issue by 2803media** [openmaptiles/openmaptiles#1458]
I want to use Varnish above the openmaptiles and my apache2 server, so I change the docker-compose.yml like that

```
version: "3"

volumes:
  pgdata:

networks:
  postgres:
    driver: bridge

services:

  postgres:
    image: "${POSTGIS_IMAGE:-openmaptiles/postgis}:${TOOLS_VERSION}"
    # Use "command: postgres -c jit=off" for PostgreSQL 11+ because of slow large MVT query processing
    # Use "shm_size: 512m" if you want to prevent a possible 'No space left on device' during 'make generate-tiles-pg'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - postgres
    ports:
      - "${PGPORT:-5432}:${PGPORT:-5432}"
    env_file: .env
    environment:
      # postgress container uses old variable names
      POSTGRES_DB: ${PGDATABASE:-openmaptiles}
      POSTGRES_USER: ${PGUSER:-openmaptiles}
      POSTGRES_PASSWORD: ${PGPASSWORD:-openmaptiles}
      PGPORT: ${PGPORT:-5432}

  import-data:
    image: "openmaptiles/import-data:${TOOLS_VERSION}"
    env_file: .env
    networks:
      - postgres

  openmaptiles-tools: &openmaptiles-tools
    image: "openmaptiles/openmaptiles-tools:${TOOLS_VERSION}"
    env_file: .env
    environment:
      # Must match the version of this file (first line)
      # download-osm will use it when generating a composer file
      MAKE_DC_VERSION: "3"
      # Allow DIFF_MODE, MIN_ZOOM, and MAX_ZOOM to be overwritten from shell
      DIFF_MODE: ${DIFF_MODE}
      MIN_ZOOM: ${MIN_ZOOM}
      MAX_ZOOM: ${MAX_ZOOM}
      #Provide BBOX from *.bbox file if exists, else from .env
      BBOX: ${BBOX}
      # Imposm configuration file describes how to load updates when enabled
      IMPOSM_CONFIG_FILE: ${IMPOSM_CONFIG_FILE}
      # Control import-sql processes
      MAX_PARALLEL_PSQL: ${MAX_PARALLEL_PSQL}
      PGDATABASE: ${PGDATABASE:-openmaptiles}
      PGUSER: ${PGUSER:-openmaptiles}
      PGPASSWORD: ${PGPASSWORD:-openmaptiles}
      PGPORT: ${PGPORT:-5432}
      MBTILES_FILE: ${MBTILES_FILE}
    networks:
      - postgres
    volumes:
      - .:/tileset
      - ./data:/import
      - ./data:/export
      - ./build/sql:/sql
      - ./build:/mapping
      - ./cache:/cache
      - ./style:/style

  update-osm:
    <<: *openmaptiles-tools
    command: import-update

  generate-changed-vectortiles:
    image: "openmaptiles/generate-vectortiles:${TOOLS_VERSION}"
    command: ./export-list.sh
    volumes:
      - ./data:/export
      - ./build/openmaptiles.tm2source:/tm2source
    networks:
      - postgres
    env_file: .env
    environment:
      MBTILES_NAME: ${MBTILES_FILE}
      # Control tilelive-copy threads
      COPY_CONCURRENCY: ${COPY_CONCURRENCY}
      PGDATABASE: ${PGDATABASE:-openmaptiles}
      PGUSER: ${PGUSER:-openmaptiles}
      PGPASSWORD: ${PGPASSWORD:-openmaptiles}
      PGPORT: ${PGPORT:-5432}

  generate-vectortiles:
    image: "openmaptiles/generate-vectortiles:${TOOLS_VERSION}"
    volumes:
      - ./data:/export
      - ./build/openmaptiles.tm2source:/tm2source
    networks:
      - postgres
    env_file: .env
    environment:
      MBTILES_NAME: ${MBTILES_FILE}
      BBOX: ${BBOX}
      MIN_ZOOM: ${MIN_ZOOM}
      MAX_ZOOM: ${MAX_ZOOM}
      # Control tilelive-copy threads
      COPY_CONCURRENCY: ${COPY_CONCURRENCY}
      #
      PGDATABASE: ${PGDATABASE:-openmaptiles}
      PGUSER: ${PGUSER:-openmaptiles}
      PGPASSWORD: ${PGPASSWORD:-openmaptiles}
      PGPORT: ${PGPORT:-5432}

  postserve:
    image: "openmaptiles/openmaptiles-tools:${TOOLS_VERSION}"
    command: "postserve ${TILESET_FILE} --verbose --serve=${OMT_HOST:-http://localhost}:${PPORT:-8090}"
    env_file: .env
    environment:
      TILESET_FILE: ${TILESET_FILE}
    networks:
      - postgres
    #ports:
    #  - "${PPORT:-8090}:${PPORT:-8090}"
    volumes:
      - .:/tileset

  varnish:
    image: eeacms/varnish
    ports:
    - "6081:6081"
    depends_on:
    - postserve
    networks:
     - postgres
    environment:
      BACKENDS: "postserve"
      BACKENDS_PORT: "8090"
      BACKENDS_PROBE_INTERVAL: "60s"
      BACKENDS_PROBE_TIMEOUT: "10s"
      BACKENDS_PROBE_URL: "/data/openmaptiles/0/0/0.pbf"
      #DNS_ENABLED: "true"

  maputnik_editor:
    image: "maputnik/editor"
    ports:
      - "8088:8888"

  tileserver-gl:
    image: "maptiler/tileserver-gl:latest"
    command:
      - --port
      - "${TPORT:-8080}"
      - --config
      - "/style/config.json"
    ports:
      - "${TPORT:-8080}:${TPORT:-8080}"
    depends_on:
      - varnish
    volumes:
      - ./data:/data
      - ./style:/style
      - ./build:/build
```

And change my apache config to use the varnish port in the proxypass and proxyreverse:

```
<VirtualHost *:80>
   ServerName tiles.example.com
   Protocols h2 h2c http/1.1

   ErrorDocument 404 /404.html

   # disable proxy for the /font-family sub-directory
   # must be placed on top of the other ProxyPass directive
   ProxyPass /font-family !
   Alias "/font-family" "/var/www/font-family"
   #HTTP proxy
   ProxyPass / http://localhost:6081/
   ProxyPassReverse / http://localhost:6081/
   ProxyPreserveHost On

   ErrorLog ${APACHE_LOG_DIR}/tileserver-gl.error.log
   CustomLog ${APACHE_LOG_DIR}/tileserver-gl.access.log combined

RewriteEngine on
RewriteCond %{SERVER_NAME} =tiles.example.com
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
   
</VirtualHost>

```

```
<IfModule mod_ssl.c>
SSLStaplingCache shmcb:/var/run/apache2/stapling_cache(128000)
<VirtualHost *:443>
   ServerName tiles.example.com
   Protocols h2 h2c http/1.1

   ErrorDocument 404 /404.html

   # disable proxy for the /font-family sub-directory
   # must be placed on top of the other ProxyPass directive
   ProxyPass /font-family !
   Alias "/font-family" "/var/www/font-family"
   #HTTP proxy
   ProxyPass / http://localhost:6081/
   ProxyPassReverse / http://localhost:6081/
   ProxyPreserveHost On

   ErrorLog ${APACHE_LOG_DIR}/tileserver-gl.error.log
   CustomLog ${APACHE_LOG_DIR}/tileserver-gl.access.log combined


SSLCertificateFile /etc/letsencrypt/live/tiles.example.com/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/tiles.example.com/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf
Header always set Strict-Transport-Security "max-age=31536000"
SSLUseStapling on
Header always set Content-Security-Policy upgrade-insecure-requests

RequestHeader set X-Forwarded-Host "tiles.example.com"
RequestHeader set X-Forwarded-Proto "https"

   
</VirtualHost>
</IfModule>
```
Then rerun docker-compose up -d
But when I access the tiles I've got a 503 error

`503 Backend fetch failed`

Any idea where is the error in configuration? 
Thanks
