### ISSUE TITLE
Missing road segment in Friuli/(north-eastern Italy)

### ISSUE THREAD

**Issue by BojanKverh** [openmaptiles/openmaptiles#331]
As the title says, there is a piece of primary road missing near (N46.2118 E13.1844) on zoom 14 (see the attached screenshot). On zoom 13 and lower it looks to be OK. 

![image](https://user-images.githubusercontent.com/12451813/31375699-b225fc4c-ada2-11e7-9b8c-4298571a08d5.png)

**Comment by jirik** [comment]
Interesting. It should be this way:
https://www.openstreetmap.org/way/363103203#map=18/46.21186/13.18430
Part of this way is rendered in transportation layer, another part is not. After brief check I see no obvious reason why it's like this. 

@BojanKverh You can try to run quickstart.sh on Italy, maybe transportation layers only, to see they were was rendered correctly.

openmaptiles.yaml:
```
tileset:
  layers:
    - layers/transportation/transportation.yaml
    - layers/transportation_name/transportation_name.yaml
  name: OpenMapTiles
  version: 3.3.0
  id: openmaptiles
...
```

`./quickstart.sh italy`
