### ISSUE TITLE
idea:  ./create_tiles.sh   <country_name>  for generating (country/city) mbtiles

### ISSUE THREAD

**Issue by ImreSamu** [openmaptiles/openmaptiles#39]
We have a ./quickstart.sh   - for start new users ..
But the expected next questions 
*   I want to generate my country, my city  .......

idea /draft specifications : 

./create_tiles.sh   ` < extract_id > `

###  V1 specification :

for downloading:
We can use https://github.com/julien-noblet/download-geofabrik  

```
go get github.com/julien-noblet/download-geofabrik
go install  github.com/julien-noblet/download-geofabrik
download-geofabrik update
download-geofabrik download  albania
---> albania.osm.pbf 
```

We need to extract the  BBOX info  from this 
And we need to create a docker-compose config
  *  like this : https://github.com/openmaptiles/openmaptiles/blob/master/docker-compose-test-override.yml

PRO:  
* easy to implement 

CON:  
* lot of osm2vectortiles extracts is missing, not perfect 

###  V2 specification :

based on:
*  https://github.com/osm2vectortiles/osm2vectortiles/blob/master/src/create-extracts/country_extracts.tsv
*  https://github.com/osm2vectortiles/osm2vectortiles/blob/master/src/create-extracts/city_extracts.tsv

We have to find an optimal osm (geofabrik?)  extracts
We have to pre-generate for an every extract a  docker-compose  extending yml file
- or we need a tool ...

~  expected output ...   

```yaml
##  OpenMapTiles service definitions for zurich_switzerland ! 
version: "2"

services:
  download-osm:
    environment:
       download_osm_url=https://s3.amazonaws.com/metro-extracts.mapzen.com/zurich_switzerland.osm.pbf
 
services:
  generate-vectortiles:
    environment:
      BBOX: "8.25,46.97,9.58,47.52"
      MIN_ZOOM: "0"
      MAX_ZOOM: "7"
```
