### ISSUE TITLE
In TileJSON (and mbtiles metadata) add content/values to description field

### ISSUE THREAD

**Issue by sfkeller** [openmaptiles/openmaptiles#401]
In TileJSON (and mbtiles metadata) the content/values of _"description"_ field in object vector_tiles is currently an empty string. See e.g. https://free.tilehosting.com/data/v3.json?key={your_api_key} and look at landuse:

```
  vector_layers:
    1: 
    ...
    3:
      maxzoom:	14
      fields:	
        class:	"String"
      minzoom:	0
      id:	"landuse"
      description:	""
```

But "description" should explain the layer, e.g. "Landuse polygons for parks, university, sports and other areas. Geometry types: polygon, line, point, label_placement." 

See e.g. this dialog from the QGIS Vector Tiles reader plugin (https://github.com/geometalab/Vector-Tiles-Reader-QGIS-Plugin/blob/master/README.md ):
![grafik](https://user-images.githubusercontent.com/43340/34688911-f683400e-f4b3-11e7-9684-b2957b1431e2.png)
