### ISSUE TITLE
Can use nominatim postgres server for openmaptiles ?

### ISSUE THREAD

**Issue by Rajavelu** [openmaptiles/openmaptiles#486]
Hi,
I have my own instance of nominatim setup for geocoding. Now i want to setup openmaptiles tileserver (which requires postgres). 
Is it possible to use my existing postgres server(setup with nominatim) for openmaptiles too?

**Comment by ImreSamu** [comment]
> Now i want to setup openmaptiles tileserver (which requires postgres).

Can you give more information - about your use case?

You don't have to set up your own -  postgres/postgis server.
see: https://github.com/openmaptiles/openmaptiles/blob/master/QUICKSTART.md tutorial 
The docker-compose.yml service includes all (server)  requirements and this is preconfigured for an average use case.
see:
*  https://github.com/openmaptiles/openmaptiles/blob/master/docker-compose.yml

see this lines:
```yml
services:
  postgres:
    image: "openmaptiles/postgis:2.9"
    volumes:
    - pgdata:/var/lib/postgresql/data
    networks:
    - postgres_conn
    ports:
     - "5432"
    env_file: .env
```


> Is it possible to use my existing postgres server(setup with nominatim) for openmaptiles too?

We don't have a support/tutorial - for this case ...  ( sorry )  

If you are an experienced "hacker" - then you can find the "openmaptiles/postgis:2.9"  - docker image source code here:   https://github.com/openmaptiles/postgis

Now ( Today )  the minimal requirements:
* Postgres >=9.6
* Postgis 2.4dev  ( ~ 2.5 )
* Geos >= 3.6
