### ISSUE TITLE
Modular Layers

### ISSUE THREAD

**Issue by lukasmartinelli** [openmaptiles/openmaptiles#5]
I am still prototyping but already working with it and quite happy with the modular approach. Really rocks.

Example of water:

```
layers/water
├── mapping.yaml
├── water.sql
└── water.yaml
```

The `layers/water/water.yaml` is the definition file of the layers.
It specifies docs, buffer size and the query and also which SQL files to get the schema from
and which imposm3 schema to use. In `datasources` we might add different `type` sources.

``` yaml
layer:
  id: "water"
  description: |
      Water polygons and linestrings representing oceans, lakes and waterways.
  buffer_size: 4
  datasource:
    query: (SELECT * FROM layer_water(!bbox!, z(!scale_denominator!))) AS t
schema:
  - ./water.sql
datasources:
  - type: imposm3
    mapping_file: ./mapping.yaml
```

This definition files are then pulled together in a `tileset` specification.

``` yaml
tileset:
  layers:
    - layers/boundary/boundary.yaml
    - layers/highway/highway.yaml
    - layers/ice/ice.yaml
    - layers/building/building.yaml
    - layers/state/state.yaml
    - layers/country/country.yaml
    - layers/place/place.yaml
    #- layers/rail/rail.yaml
    - layers/urban/urban.yaml
    - layers/water/water.yaml
    - layers/landcover/landcover.yaml
  name: OSM2VectorTiles v3.0
  description: "Free global vector tiles from OpenStreetMap. http://osm2vectortiles.org"
  attribution: "<a href=\"http://www.openstreetmap.org/about/\" target=\"_blank\">&copy; OpenStreetMap contributors</a>"
  center: [-12.2168, 28.6135, 4]
  maxzoom: 14
  minzoom: 0
  defaults:
    srs: +proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over
    datasource:
      srid: 900913
```

With the mapping containing the imposm3 mapping and generalized tables.

``` yaml
generalized_tables:
  water_polygon_gen3:
    source: water_polygon
    sql_filter: area>9000000.0
    tolerance: 350.0
  water_polygon_gen2:
    source: water_polygon
    sql_filter: area>1000000
    tolerance: 200.0
  water_polygon_gen1:
    source: water_polygon
    sql_filter: area>500000
    tolerance: 100.0
tables:
  water_polygon:
    fields:
    - name: osm_id
      type: id
    - name: geometry
      type: validated_geometry
    - name: area
      type: pseudoarea
    - key: name
      name: name
      type: string
    - name: name_en
      key: name:en
      type: string
    filters:
      exclude_tags:
      - [ "covered", "yes" ]
    mapping:
      landuse:
      - reservoir
      natural:
      - water
      - bay
      waterway:
      - river
      - riverbank
      - stream
      - canal
      - drain
      - ditch
    type: polygon
  water_linestring:
    fields:
    - name: osm_id
      type: id
    - name: geometry
      type: geometry
    - name: waterway
      type: mapping_value
    - key: name
      name: name
      type: string
    - name: name_en
      key: name:en
      type: string
    mapping:
      waterway:
      - stream
      - river
      - canal
      - drain
      - ditch
    type: linestring

```

I switched to imposm3 now because it integrates much better with modular layers - actually switching the queries over from one schema to another is not much work.

I have a Python script now called `omtgen.py` (for Open Map Tile generation tool) which takes care of generating tm2source, imposm3 mapping and aggregating all the SQL of all the layers.

@klokan Could you create a repo `omtgen` where I develop the generation tool for OpenMapTiles? Better name for the CLI also welcome.

The generation tool must be able to do:
- [x] Create tm2source (in future other outputs as well - including PostgreSQL native generation #3)
- [x] Create imposm3 mapping
- [x] Collect SQL
- [x] Generate Markdown documentation
