### ISSUE TITLE
[building] exclude tags building=no ; building=unknown ?  

### ISSUE THREAD

**Issue by ImreSamu** [openmaptiles/openmaptiles#69]
Related to https://github.com/openmaptiles/openmaptiles/blob/master/layers/building/mapping.yaml

Q: 
Probably better to exclude the [building=no](http://taginfo.openstreetmap.org/tags/building=no#combinations
)  ?
and exclude other tagging problems ?

proposal :  imposm3 mapping     with:  # taginfo count 

```yaml
    filters:
      exclude_tags:
      - [ "building", "no" ]              # 12616 
      - [ "building", "none" ]            # 28
      - [ "building", "No" ]              # 11 
```

I am not sure 
```yaml
      - [ "building", "unknown" ]         # 240
      - [ "building", "unkown" ]          # 10 
```
