### ISSUE TITLE
Allow specifying possible values for Fields in Layer Spec

### ISSUE THREAD

**Issue by lukasmartinelli** [openmaptiles/openmaptiles#76]
One can express the possible values for fields in the documentation string of the field or in description but for generating better documentation it makes sense to add a `description` and `values` attribute to the field object.

Values can be a simple set right now (we can perhaps extend it to support numeric ranges but it goes quite far with just a list).

(this can also be used to generate metadata used by editors like Maputnik).

Instead of this.

```yaml
layer:
  description: |
      The park layer contains parks from OpenStreetMap tagged with either [`boundary=national_park`](http://wiki.openstreetmap.org/wiki/Tag:boundary%3Dnational_park) or [`leisure=nature_reserve`](http://wiki.openstreetmap.org/wiki/Tag:leisure%3Dnature_reserve).
  fields:
    class: |
        Either `national_park` or `nature_reserve`.
```

```yaml
layer:
  description: |
      The park layer contains parks from OpenStreetMap tagged with either [`boundary=national_park`](http://wiki.openstreetmap.org/wiki/Tag:boundary%3Dnational_park) or [`leisure=nature_reserve`](http://wiki.openstreetmap.org/wiki/Tag:leisure%3Dnature_reserve).
  fields:
    class:
      description: Differentiate between different park types. The `class` value is the value from the `boundary` or `leisure` tag. 
      values:
      - `national_park`
      - `nature_reserve`
```

More examples (for place).

Before 

```yaml
layer:
  id: "place"
  description: |
      The place layer consists out of [countries](http://wiki.openstreetmap.org/wiki/Tag:place%3Dcountry),
      [states](http://wiki.openstreetmap.org/wiki/Tag:place%3Dstate) and [cities](http://wiki.openstreetmap.org/wiki/Key:place).
      Apart from the roads this is also one of the more important layers to create a beautiful map.
      We suggest you use different font styles and sizes to create a text hierarchy.
  fields:
    name: The OSM [`name`](http://wiki.openstreetmap.org/wiki/Key:name) value of the POI.
    name_en: The english `name:en` value if available.
    class: |
        Distinguish between `country`, `state` and other city classes like
        `city`, `town`, `village`, `hamlet`, `suburb`, `neighbourhood` or `isolated_dwelling`.
        Use this to separately style the different places according to their importance (usually country and state different
        than cities).
    rank: |
        Countries, states and the most important cities all have a `rank` to boost their importance on the map.
        The `rank` field for counries and states ranges from `1` to `6` while the `rank` field for
        cities ranges from `1` to `10` for the most important cities and continues from `10` serially based
        on the local importance of the city (derived from population and city class).
        Use the `rank` field to build a text hierarchy.
        The rank value is a combination of the Natural Earth `scalerank`, `labelrank` and `datarank` values for countries
        and states and for cities consists out of a shifted Natural Earth `scalerank` combined with a local rank
        within a grid for cities that do not have a Natural Earth `scalerank`.
```

With the new field structure.

```yaml
layer:
  id: "place"
  description: |
      The place layer consists out of [countries](http://wiki.openstreetmap.org/wiki/Tag:place%3Dcountry),
      [states](http://wiki.openstreetmap.org/wiki/Tag:place%3Dstate) and [cities](http://wiki.openstreetmap.org/wiki/Key:place).
      Apart from the roads this is also one of the more important layers to create a beautiful map.
      We suggest you use different font styles and sizes to create a text hierarchy.
  fields:
    name:
        description: The OSM [`name`](http://wiki.openstreetmap.org/wiki/Key:name) value of the POI.
    name_en:
         description: The english `name:en` value if available.
    class: 
        description: ...
        values:
        - city
        - town
        - village
        - hamlet
        - suburb
        - neighbourhood
        - isolated_dwelling
    rank:
        description: ...
        values:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 10
```
