### ISSUE TITLE
Strategy for dependent layer's code

### ISSUE THREAD

**Issue by nyurik** [openmaptiles/openmaptiles#796]
We currently have some hidden cross-layer dependencies that cannot be easily tracked.

For example, `waterway_brunnel` function is used in [waterway](https://github.com/openmaptiles/openmaptiles/blob/master/layers/waterway/waterway.sql#L1) and [water](https://github.com/openmaptiles/openmaptiles/blob/master/layers/water/water.sql#L56) layers. At the moment the declaration is identical, but this only works if functions are imported sequentially, and we don't accidentally modify just one of them and forgetting the other.

Another example is `highway_class` function, declared in `transportation` layer, but used in both `transportation` and `transportation_name` layers.

One possible solution is to have dependency tracking: each layer can define what other layers it depends on. So `transportation_name` would list `transportation` as a dependency.

```yaml
layer:
  id: "transportation_name"
  requires: "transportation"   # this can be a string or a list of strings
```
