### ISSUE TITLE
[proposal] multi language support ; language neutrality ; hstore for all osm name ;  simple config   

### ISSUE THREAD

**Issue by ImreSamu** [openmaptiles/openmaptiles#80]
### Problem:

* Which languages supported and why ?  
* language neutrality 

### Proposal 

So I am thinking about multi language support .. 

in the future I would like to Experimenting  this plan  :  

####  Step 1
- [ ] add  `hstore_keep`  mapping  to imposm3 ( upstream ? )
   *   https://github.com/ImreSamu/imposm3_fieldtypes/blob/master/mapping/fieldtype_hstore_tags_keep.go

and store all openstreetmap name:*  tags 
 *  http://taginfo.openstreetmap.org/search?q=name%3A
 *  mapping :  
```yaml
-   name: name_all
    key: null
    type: hstore_tags_keep
    args:
        keep_keys:
             name:*
```
####  Step 2
- [ ] add `name_all::hstore`   field to layers

####  Step 3
- [ ] add requested languages for the configurations 
```yaml
tileset:
  requested_languages:  
    - en
    - hu
    - de
    - es
  layers:
    - layers/boundary/boundary.yaml
    - layers/place/place.yaml
    - layers/poi/poi.yaml
  name: OpenMapTiles v1.0
  description: "A tileset showcasing all layers in OpenMapTiles. http://openmaptiles.org"
  attribution: "<a href=\"http://www.openstreetmap.org/about/\" target=\"_blank\">&copy; OpenStreetMap contributors</a>"
  center: [-12.2168, 28.6135, 4]
```

####  Step 4
- [ ]  generate to final query for  tm2source ( by `openmaptiles-tools` based on `requested_languages`  )
```sql
query: (SELECT geometry, name 
           ---  requested_languages : 
           ,name_all->'name:en' as name_en
           ,name_all->'name:hu' as name_hu
           ,name_all->'name:de' as name_de
           ,name_all->'name:es' as name_es
           ----------------------------------------------
          , class, rank FROM layer_place(!bbox!, z(!scale_denominator!), !pixel_width!)) AS t
```

#### Summary 
if the users want more or less languages , they need modify 1 simple config file ..
```
  requested_languages:  
    - en
    - hu
    - de
    - es
```

### Edit1    ( based on comments ) 
* other similar fields ( based on Mapzen ) :  
  *  `alt_name:*`  ->  `requested_alt_languages`
  *  `old_name:*` ->  `requested_old_languages`
