### ISSUE TITLE
[transportation_name] layer : missing `network` field from the datasource.query  SQL select

### ISSUE THREAD

**Issue by ImreSamu** [openmaptiles/openmaptiles#92]
just for documenting:
source:  `/layers/transportation_name/transportation_name.yaml`

The `network` field is missing from the layer.datasource.query  - SQL select list
```yaml
query: (SELECT geometry, name, ref, ref_length, class::text FROM layer_transportation_name(!bbox!, z(!scale_denominator!))) AS t
```
https://github.com/openmaptiles/openmaptiles/blob/master/layers/transportation_name/transportation_name.yaml#L34

But  listed in the `fields`  

```yaml
  fields:
    ... 
    network: The OSM [`network`](http://wiki.openstreetmap.org/wiki/Key:network) tag of the road.
```
